name: Deploy Discord bot to Render
run-name: Deploy new chat version to render
on:
    push:
        branches:
            - main
jobs:
    Push-image-to-ghcr:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Setup NodeJs
              uses: actions/setup-node@v4
              with: 
                node-version: 20

            - name: Prepare .env file
              env: 
                DISCORD_TOKEN: ${{secrets.DISCORD_TOKEN}}
                GUILD_ID: ${{secrets.GUILD_ID}}

              run: |  
                touch .env
                echo DISCORD_TOKEN = "$env.DISCORD_TOKEN" >> .env
                echo GUILD_ID = "$env.GUILD_ID" >> .env
            
            - name: Login to Github container Registry
              env: 
                CR_PAT: ${{secrets.CR_PAT}}
              run: echo ${{env.CR_PAT}} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Lower case github owner
              id: toLowerCase
              run: INPUT=${{github.repository_owner }} echo "::set-output name=lowerCaseValue::${INPUT,,}"
            - name: Build Docker image
              run:  docker build -t ghcr.io/${{steps.toLowerCase.outputs.lowerCaseValue}}/my_discord_bot:latest .

            - name: Push Docker image
              run:  docker push ghcr.io/${{steps.toLowerCase.outputs.lowerCaseValue}}/my_discord_bot:latest
            

 



