name: Deploy Discord bot to Render
run-name: Deploy new chat version to render
on:
    push:
        branches:
            - main
jobs:
    Push-image-to-ghcr:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Setup NodeJs
              uses: actions/setup-node@v4
              with: 
                node-version: 20

            - name: Prepare .env file
              env: 
                DISCORD_TOKEN: ${{secrets.DISCORD_TOKEN}}
                GUILD_ID: ${{secrets.GUILD_ID}}

              run: |  
                touch .env
                echo DISCORD_TOKEN = "${{env.DISCORD_TOKEN}}" >> .env
                echo GUILD_ID = "${{env.GUILD_ID}}" >> .env
            
            - name: Login to Github container Registry
              env: 
                CR_PAT: ${{secrets.CR_PAT}}
              run: echo ${{env.CR_PAT}} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Lower case github owner
              run: |
                INPUT=${{github.repository_owner}}
                LOWERCASE=$(echo "$INPUT" | tr '[:upper:]' '[:lower:]')
                echo "Lowercase: $LOWERCASE"
                echo "lowercase_output=$LOWERCASE" >> $GITHUB_ENV

            - name: Build Docker image
              run:  docker build -t ghcr.io/${{env.lowercase_output}}/my_discord_bot:latest .

            - name: Push Docker image
              run:  docker push ghcr.io/${{env.lowercase_output}}/my_discord_bot:latest

            - name: Deploy to Render with Image URL
              env:
                RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
              run: |
                curl -X POST \
                -H "Authorization: Bearer ${{env.RENDER_API_KEY}}" \
                -H "Content-Type: application/json" \
                -d '{
                  "serviceId": "YOUR_SERVICE_ID",
                  "imageDeploy": {
                    "image": "ghcr.io/${{ env.lowercase_output }}/my_discord_bot:latest"
                  }
                }' \
                https://api.render.com/v1/services/srv-ct0r6ortq21c73ei1p0g/deploys 
                  

 



